---
- name: Set timezone to Asia/jerusalem
  timezone:
    name: Asia/Jerusalem

- name: Install system required packages
  package:
    name:
      - python3
      - python3-pip
      - jq
      - wget
      - git
      - curl
      - gcc
      - findutils
      - make
      - rsync 
      - tar
    state: present

# TODO: move this to the user, does'nt need to be with root
- name: Set up pip dependencies
  pip:
    name:
      - toml
      - github.py

# TODO: check if works
- name: Set selinux to permissive
  selinux:
    policy: targeted
    state: permissive

