
- name: configure systemd service for chain_restart
  when: not use_cosmovisor
  template:
    src: chain.service.j2
    dest: "/etc/systemd/system/{{node_service_name}}.service"

- name: Restart journalctl so that the logs may flow
  systemd:
    state: restarted
    name: systemd-journald

- name: Enable chain systemd service
  when: not use_cosmovisor
  systemd:
    daemon_reload: true
    state: stopped
    enabled: true
    name: "{{node_service_name}}"

- name: Start chain systemd service
  when: (not use_cosmovisor) and (not reboot | default(false) | bool)
  systemd:
    daemon_reload: true
    state: restarted
    enabled: true
    name: "{{node_service_name}}"
  tags:
    - chain_start
    - chain_restart

